### ISSUE TITLE
Añadir contenido operador 'Suma 1'  -> (x++, ++x)

### ISSUE THREAD

**Issue by ivncd** [aafrecct/acm-curso-progra#1]
Respecto a esto:

>
>[https://github.com/aafrecct/acm-curso-progra/blob/main/contenido/02-Java/JavaTipos.md](https://github.com/aafrecct/acm-curso-progra/blob/main/contenido/02-Java/JavaTipos.md)
>
>Por último, podemos introducir algunos operadores en Java:
>```java
>// Suma, resta, multiplicación
>int n = 15 + 10 - 5 * 5;
>// División
>double d = 10 / 5;
>// Módulo
>int m = 170 % 3;
>// Suma 1
>n++;
>++n;
>// Suma de Strings
>String saludo = "Hola " + "Antonio"
>```

Podriais añadir para marcar exactamente cuando se realiza una suma en estos casos: 

```java
int x = 0;
console.log(x++); // 0
console.log(x); // 1
x = 0;
console.log(++x) // 1
```
<br/>
Quedaria asi:

```java
// Suma, resta, multiplicación
int n = 15 + 10 - 5 * 5;
// División
double d = 10 / 5;
// Módulo
int m = 170 % 3;
// Suma 1
int x = 0;
console.log(x++); // 0
console.log(x); // 1
x = 0;
console.log(++x) // 1
// Suma de Strings
String saludo = "Hola " + "Antonio"
```

Estoy en primero y esto me llamo mucho la atención

**Comment by aafrecct** [comment]
he añadido una explicación justo donde dices, aunque quizás mi solución es un poco más dificil de entender que lo que tu propones :sweat_smile:
https://github.com/aafrecct/acm-curso-progra/blob/1f4d94a7f1ae36c3f788eaa1d082597229aa1d56/contenido/02-Java/JavaTipos.md?plain=1#L45
